#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version

In [5]:
print(np.__version__)

1.19.2


#### 3. Create a null vector of size 10 (★☆☆)

In [6]:
null_vect = np.zeros(10)

In [7]:
print(null_vect)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


### Problem 4: Given a numpy array whose underlying data is of 'int32' type. Change the dtype of the given object to 'float64'.

In [11]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [13]:
np.array([1,2,3,4,5], dtype =float)

array([1., 2., 3., 4., 5.])

6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [14]:
null_vect = np.zeros(10)

In [15]:
null_vect

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
null_vect[9] = 1

In [17]:
null_vect

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 1.])

#### 4. Numpy where Problem

Say we have a numpy array A 

[[1 2 3]
 [4 5 6]]

Create a new matrix with Indices of elements <4

Output
Elements which are <4
array([1, 2, 3])

In [20]:
A = np.array([[1,2,3],[4,5,6]])

In [38]:
A[A<4]

array([1, 2, 3])

#### 5. Create a vector with values ranging from 10 to 49 (★☆☆)

In [39]:
np.arange(10,49)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

#### 6. Reverse a vector (first element becomes last) (★☆☆)

In [43]:
my_vect = np.arange(1,10)

In [50]:
my_vect

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
my_vect[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

#### 7. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [54]:
A=np.arange(0,9)

In [55]:
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [56]:
A.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 8. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [57]:
non_zero_elements = np.array([1,2,0,0,4,0])

In [63]:
np.nonzero(non_zero_elements)

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [64]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [67]:
np.random.random((3,3,3))

array([[[0.23248963, 0.39565029, 0.531861  ],
        [0.50596151, 0.73463647, 0.31892111],
        [0.38807388, 0.75750637, 0.47046392]],

       [[0.97852632, 0.2038455 , 0.54925565],
        [0.33534491, 0.2857459 , 0.89888143],
        [0.02689817, 0.86137567, 0.24702362]],

       [[0.25648682, 0.90269484, 0.38892478],
        [0.69536002, 0.98460059, 0.36095305],
        [0.03744183, 0.18332489, 0.8427062 ]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [73]:
x = np.random.random((10,10))

In [74]:
x

array([[0.67587075, 0.21702496, 0.59122664, 0.7008216 , 0.28373985,
        0.08251917, 0.57474825, 0.94611395, 0.10141169, 0.92752856],
       [0.29430682, 0.24935846, 0.54664582, 0.26896262, 0.90651468,
        0.92073039, 0.49975795, 0.58448785, 0.78481916, 0.30413636],
       [0.08758159, 0.31326159, 0.65019639, 0.61893694, 0.73384828,
        0.30658346, 0.74238073, 0.61961543, 0.12563505, 0.11644197],
       [0.79162635, 0.51134709, 0.0498218 , 0.17533141, 0.3811855 ,
        0.27005701, 0.79263014, 0.10465207, 0.12538269, 0.04962704],
       [0.62648445, 0.20958249, 0.85083695, 0.96845112, 0.32675206,
        0.54701381, 0.95380838, 0.99935713, 0.23845117, 0.96948625],
       [0.7581969 , 0.96726437, 0.58323604, 0.50132158, 0.4875052 ,
        0.59043774, 0.78219199, 0.22608891, 0.04726756, 0.4919432 ],
       [0.80834352, 0.46405686, 0.65529695, 0.46127506, 0.68431493,
        0.06873323, 0.46610984, 0.08212024, 0.41329757, 0.67897651],
       [0.59422862, 0.195698  , 0.5080594

In [75]:
x.max()

0.9993571347246643

In [76]:
x.min()

0.03283090460712257

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [77]:
rand_vect = np.random.random(30)

In [78]:
rand_vect

array([0.78428628, 0.28707211, 0.92468434, 0.96602376, 0.07020257,
       0.46562649, 0.26294907, 0.26416045, 0.09482948, 0.82228158,
       0.23281654, 0.7879723 , 0.64258846, 0.24590155, 0.93649671,
       0.32265504, 0.2304544 , 0.66946206, 0.32673345, 0.76277474,
       0.40915712, 0.00685038, 0.75383489, 0.65185237, 0.60529461,
       0.64894345, 0.8122539 , 0.53076433, 0.67970043, 0.01731163])

In [79]:
rand_vect.mean()

0.5071978167370956

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [80]:
two_d_array = np.ones((5,5))

In [81]:
two_d_array

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [96]:
two_d_array[1:-1,1:-1] =0

In [97]:
two_d_array

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [98]:
x = np.ones((3,3))
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [103]:
y=np.pad(x,pad_width=1,mode='constant',constant_values=0)

In [104]:
y

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [106]:
np.nan * 0

nan

In [107]:
np.nan == np.nan

False

In [108]:
np.inf > np.nan

False

In [109]:
np.nan - np.nan

nan

In [110]:
np.nan in set([np.nan])

True

In [111]:
0.3 == 3 * 0.1

False

#### 18. Create a 4x4 matrix with values 0,1,2,3 just below the diagonal (★☆☆)

In [113]:
Z = np.diag(1+np.arange(4),k=-1)

In [114]:
Z

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
---



In [117]:
x = np.zeros(10)
x[4] = 1

In [118]:
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 22. Normalize a 5x5 random matrix (★☆☆) Say X is 5*5 numpy array  Normalize i.e X - mean(X) / Standard Deviation of X [link text](https://)

In [119]:
x= np.random.random((3,3))
print("Original Array:")
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("After normalization:")
print(x)

Original Array:
[[0.6800876  0.55674028 0.52293268]
 [0.77077106 0.91075775 0.23396209]
 [0.16797352 0.47599832 0.65086025]]
After normalization:
[[0.68945201 0.52339124 0.47787654]
 [0.81153788 1.         0.08883949]
 [0.         0.41468947 0.65010364]]


#### 23. Numpy where Problem

Say we have a numpy array A 

[[1 2 3]
 [4 5 6]]

Create a new matrix with Indices of elements <4

Output
Elements which are <4
array([1, 2, 3])

In [120]:
A = np.array([[1,2,3],[4,5,6]])
A[A<4]

array([1, 2, 3])

#### 24. Do a dot product of 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [121]:
x = np.random.random((5,3))
print("First array:")
print(x)
y = np.random.random((3,2))
print("Second array:")
print(y)
z = np.dot(x, y)
print("Dot product of two arrays:")
print(z)

First array:
[[0.39492508 0.13684348 0.14222232]
 [0.24651803 0.8760309  0.12646337]
 [0.62123991 0.62679273 0.24372446]
 [0.39664394 0.72136224 0.1262165 ]
 [0.23595278 0.69816069 0.16050788]]
Second array:
[[0.67388242 0.39943011]
 [0.57530314 0.86238869]
 [0.39306562 0.27526088]]
Dot product of two arrays:
[[0.40076226 0.31490548]
 [0.7198159  0.88875628]
 [0.87503819 0.8557687 ]
 [0.73190471 0.81526864]
 [0.6237486  0.74051407]]


#### 25. Consider two random array A and B, check if they are equal (★★☆)

In [130]:
A = np.random.random(5)
B = np.random.random(5)

In [131]:
print(A)
print(B)

[0.65005832 0.01177251 0.43234339 0.26111573 0.22838523]
[0.12789722 0.25631792 0.20075749 0.39954638 0.05938197]


In [132]:
np.equal(A,B)

array([False, False, False, False, False])

In [133]:
np.allclose(A,B)

False

#### 26. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [134]:
x = np.random.random(10)

In [135]:
x

array([0.19564992, 0.99303278, 0.50758535, 0.56235483, 0.60859734,
       0.31773111, 0.32355181, 0.23097187, 0.56772079, 0.69901906])

In [144]:
x[x.argmax()] = 0

In [145]:
x

array([0.19564992, 0.        , 0.50758535, 0.56235483, 0.60859734,
       0.31773111, 0.32355181, 0.23097187, 0.56772079, 0.69901906])

#### 27. Subtract the mean of each row of a matrix (★★☆):

In [148]:
X = np.random.rand(3,3)
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

[[0.58675775 0.84077627 0.62284124]
 [0.01765577 0.69699609 0.2625895 ]
 [0.74951062 0.91326339 0.3536885 ]]

Subtract the mean of each row of the said matrix:

[[-0.09670067  0.15731785 -0.06061718]
 [-0.30809135  0.37124897 -0.06315762]
 [ 0.07735645  0.24110922 -0.31846567]]
